---
- name: search for the latest rhel 7 ami
  ec2_ami_find:
    region: eu-central-1
    owner: "309956199498"
    name: "RHEL-7.3*"
  register: find_results

- debug: 
    msg: "{{find_results}}"
    verbosity: 2
    
- ec2_vpc_net_facts:
    region: eu-central-1
    filters:
      "tag:Name": Production VPC
  register: network

- set_fact:
    vpc_id: "{{ network.vpcs[0].id }}"

- ec2_vpc_subnet_facts:
    region: eu-central-1
    filters:
      vpc-id: "{{ vpc_id }}"
  register: vpc_nets
- set_fact:
    subnets: "{{ vpc_nets.subnets | map(attribute='id') | list }}"

- ec2_group:
    name: webservers
    region: eu-central-1
    description: Security group to allow public web traffic to the unicorn.rentals API
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 5000
        to_port: 5000
        cidr_ip: 0.0.0.0/0
  register: web_sg
- debug:
    msg: "Created VPC security group called webservers, ID {{ web_sg.group_id }} to take web traffic"
    verbosity: 2

- ec2_group:
    name: public-ssh
    region: eu-central-1
    description: Security group for public SSH traffic (you may want to restrict this a bit...)
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: ssh_sg
- debug:
    msg: "Created VPC security group called public-ssh, ID {{ ssh_sg.group_id }} for granting SSH access to servers."
    verbosity: 2

- ec2:
    region: eu-central-1
    key_name: "{{ ssh_key_name }}"
    assign_public_ip: yes
    image: "{{find_results.results[0].ami_id}}"
    group_id:
      - "{{ web_sg.group_id }}"
      - "{{ ssh_sg.group_id }}"
    instance_tags:
      Name: Ansible_plz_work
    instance_type: t2.micro
    monitoring: yes
    vpc_subnet_id: "{{ subnets[0] }}"
    user_data: "{{ lookup('template', 'templates/userdata.txt.j2') }}"

